apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nicru-dns
spec:
  acme:
    email: mail@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-letsencrypt-private-key
    solvers:
      - dns01:
          webhook:
            config:
              nicruTokenSecretRef:
                name: nicru-tokens
                key: ACCESS_TOKEN
            groupName: {{ .Values.groupName }}
            solverName: nicru-dns